version: '3'


services:
  fastapi:
    build: .
    command: uvicorn main:app --host 0.0.0.0
    ports:
      - "8888:8000"
    networks:
      - app-fastapi

networks:
  app-fastapi:
    driver: bridge